# flake8: noqa

# In[]:
# Controls for webapp
# Updated AREA_NAMES
AREA_NAMES = {
    "01": "Kaivopuisto - Ullanlinna",
    "02": "Kaartinkaupunki",
    "03": "Viherlaakso",
    "04": "Veromiehenkylä",
    "05": "Santahamina",
    "06": "Espoon Keskus",
    "07": "Matinkylä",
    "08": "Etelä-Leppävaara",
    "09": "Koivukylä-Havukoski",
    "10": "Tapiola",
    "11": "Tapanila",
    "12": "Pikku Huopalahti",
    "13": "Kauklahti",
    "14": "Helsinki Keskusta - Etu-Töölö",
    "15": "Ruskeasuo",
    "16": "Malminkartano",
    "17": "Etu-Vallila - Alppila",
    "18": "Karakallio",
    "19": "Eira - Hernesaari",
    "20": "Kontula - Vesala",
    "21": "Lassila",
    "22": "Roihupellon teollisuusalue",
    "23": "Länsi-Pasila",
    "24": "Tapaninvainio",
    "25": "Kivihaka",
    "26": "Niipperi",
    "27": "Vartioharju",
    "28": "Sörnäinen",
    "29": "Länsi-Herttoniemi",
    "30": "Myllypuro",
    "31": "Tuomarila-Suvela",
    "32": "Pohjois-Haaga",
    "33": "Punavuori",
    "34": "Östersundom",
    "35": "Rekola",
    "36": "Gumböle-Karhusuo",
    "37": "Jakomäki - Alppikylä",
    "38": "Ylästö",
    "39": "Ruskeasanta-Ilola",
    "40": "Pajamäki",
    "41": "Kaivoksela",
    "42": "Kilo",
    "43": "Tuomarinkylä-Torpparinmäki",
    "44": "Espoonlahti",
    "45": "Toukola-Vanhakaupunki",
    "46": "Pihlajamäki",
    "47": "Ilmala",
    "48": "Varisto",
    "49": "Koskela-Helsinki",
    "50": "Korso",
    "51": "Puotinharju",
    "52": "Tammisalo",
    "53": "Hämeenkylä",
    "54": "Käpylä",
    "55": "Nupuri-Nuuksio",
    "56": "Jokiniemi",
    "57": "Pohjois-Meilahti",
    "58": "Länsimäki",
    "59": "Pohjois-Vuosaari",
    "60": "Kuusisaari-Lehtisaari",
    "61": "Malmi",
    "62": "Reimarla",
    "63": "Henttaa",
    "64": "Haukilahti",
    "65": "Mikkola",
    "66": "Pohjois-Tapiola",
    "67": "Itä-Hakkila",
    "68": "Latokaski",
    "69": "Suvisaaristo",
    "70": "Itäkeskus-Marjaniemi",
    "71": "Lintuvaara",
    "72": "Suomenlinna",
    "73": "Otsolahti",
    "74": "Leinelä",
    "75": "Konala",
    "76": "Kirkonkylä-Veromäki",
    "77": "Kulosaari",
    "78": "Puistola",
    "79": "Sepänkylä-Kuurinniitty",
    "80": "Hakunila",
    "81": "Tikkurila",
    "82": "Herttoniemi",
    "83": "Viikki",
    "84": "Etelä-Laajasalo",
    "85": "Siltamäki",
    "86": "Kannelmäki",
    "87": "Tammisto",
    "88": "Otaniemi",
    "89": "Seutula",
    "90": "Myyrmäki",
    "91": "Mankkaa",
    "92": "Kivistö",
    "93": "Nikinmäki",
    "94": "Jätkäsaari",
    "95": "Oulunkylä-Patola",
    "96": "Vattuniemi",
    "97": "Kaitaa",
    "98": "Uusmäki",
    "99": "Aurinkolahti",
    "100": "Etelä-Haaga"
}


WELL_COLORS = dict(
    GD="#FFEDA0",
    GE="#FA9FB5",
    GW="#A1D99B",
    IG="#67BD65",
    OD="#BFD3E6",
    OE="#B3DE69",
    OW="#FDBF6F",
    ST="#FC9272",
    BR="#D0D1E6",
    MB="#ABD9E9",
    IW="#3690C0",
    LP="#F87A72",
    MS="#CA6BCC",
    Confidential="#DD3497",
    DH="#4EB3D3",
    DS="#FFFF33",
    DW="#FB9A99",
    MM="#A6D853",
    NL="#D4B9DA",
    OB="#AEB0B8",
    SG="#CCCCCC",
    TH="#EAE5D9",
    UN="#C29A84",
)